name: Run MATLAB Tests in GIritHub-hosted Runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB tests and Generate Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: Simulink Simulink_Test Simulink_Coverage
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v2
        with:
          test-results-junit: test-result/results.xml
          test-results-pdf: test-result/results.pdf
          test-results-simulink-test: test-result/results.mldatx          
      - name: Update artifacts
        uses: actions/upload-artifact@v4
        with:
         name: test-results
         path: test-results
         